/**
 * Corpus de frases de ejemplo por intent para el NLU semántico. PURO (solo
 * datos). Las claves son los IntentId como string (incl. 'data-query' y
 * 'advice') para no acoplarse al union mientras se cablea. El seed
 * (`scripts/seed-intent-examples.ts`) embebe cada frase y la persiste; el
 * classifier semántico hace kNN y mapea el `intent` ganador de vuelta a IntentId.
 *
 * Variedad deliberada: tuteo y voseo, parafraseo, coloquialismos CO. Cuantas más
 * formas naturales por intent, mejor generaliza el embedding a frases nuevas.
 */
export const INTENT_CORPUS: Record<string, string[]> = {
  'show-balance': [
    'cuál es mi saldo total',
    'cuánto tengo en total',
    'cuánta plata tengo',
    'cuánto dinero tengo ahora',
    'mi saldo',
    'cuánto hay en mis cuentas',
    'cuánto me queda en total',
    'a cuánto asciende mi dinero',
    'mostrame mi balance',
    'qué tan parado estoy de plata',
    'cuánto tengo disponible',
    'resumen de mis saldos',
  ],
  'account-detail': [
    'saldo de mi cuenta de ahorros',
    'cuánto tengo en el débito',
    'cuánto hay en mi cuenta corriente',
    'saldo de la tarjeta',
    'cuánta plata tengo en bancolombia',
    'cuánto me queda en nequi',
    'movimientos de mi cuenta de ahorros',
    'cómo va mi cuenta principal',
    'detalle de mi cuenta nómina',
  ],
  'spend-by-category': [
    'cuánto gasté este mes',
    'en qué se me va la plata',
    'en qué estoy gastando más',
    'cuánto gasté en restaurantes',
    'gastos de transporte este mes',
    'cuánto llevo gastado en mercado',
    'en qué se fue mi sueldo',
    'cuánto gasto en comida',
    'mis gastos por categoría',
    'dónde se está yendo mi dinero',
    'cuánto he gastado en gasolina',
    'desglose de mis gastos',
  ],
  'top-merchants': [
    'dónde gasté más',
    'en qué comercios gasto más',
    'mis tiendas con más gasto',
    'top de comercios del mes',
    'a qué negocios les pago más',
    'en qué lugares gasto la plata',
    'cuáles son mis comercios principales',
  ],
  'budget-status': [
    'cómo van mis presupuestos',
    'cómo voy con el presupuesto',
    'me estoy pasando del presupuesto',
    'estado de mis topes de gasto',
    'cuánto me queda de presupuesto',
    'qué presupuesto está en riesgo',
    'voy bien con mis límites de gasto',
  ],
  'upcoming-payments': [
    'qué pagos se vienen',
    'qué tengo que pagar pronto',
    'próximos vencimientos',
    'qué se viene esta semana de pagos',
    'cuánto tengo que pagar este mes',
    'qué cuentas tengo por pagar',
    'mis próximos pagos',
  ],
  runway: [
    'cuánto me dura la plata',
    'hasta cuándo me alcanza el dinero',
    'cuánto me alcanza con lo que tengo',
    'me llega la plata a fin de mes',
    'cuántos días me dura lo que tengo',
    'mi runway financiero',
    'aguanto hasta el otro pago',
  ],
  'compare-month': [
    'gasté más que el mes pasado',
    'comparar este mes con el anterior',
    'cómo va este mes contra el pasado',
    'estoy gastando más que antes',
    'diferencia de gasto con el mes pasado',
    'este mes gasté más o menos',
  ],
  'biggest-charge': [
    'cuál fue mi gasto más caro',
    'el gasto más grande del mes',
    'mi compra más cara',
    'el cargo más alto que tuve',
    'cuál fue el movimiento más grande',
    'mis gastos más grandes',
  ],
  subscriptions: [
    'qué suscripciones tengo',
    'mis pagos recurrentes',
    'qué pago todos los meses',
    'cuánto gasto en suscripciones',
    'qué cargos fijos tengo',
    'mis mensualidades',
  ],
  'savings-progress': [
    'cómo voy con el ahorro',
    'cuánto he ahorrado',
    'voy bien con mi meta de ahorro',
    'cuánto llevo ahorrado este año',
    'cómo va mi meta',
    'estoy ahorrando lo suficiente',
  ],
  'debt-overview': [
    'cuánto debo',
    'mis deudas',
    'cuánto debo en total',
    'cómo van mis préstamos',
    'cuánto me falta por pagar de deudas',
    'resumen de lo que debo',
  ],
  'insights-active': [
    'qué detectaste',
    'qué encontraste raro en mis finanzas',
    'hay alguna anomalía',
    'qué has notado en mis gastos',
    'mis alertas',
    'qué debería revisar',
  ],
  'search-transactions': [
    'busca pagos a uber',
    'encuentra transacciones de netflix',
    'movimientos de rappi',
    'busca compras en éxito',
    'transacciones de spotify',
    'mostrame los pagos a claro',
  ],
  'monthly-summary': [
    'resumen del mes',
    'cómo cerró el mes',
    'dame un panorama de mis finanzas',
    'recap del mes',
    'cómo me fue este mes',
    'resumen general',
  ],
  'dormant-money': [
    'tengo cuentas sin movimiento',
    'dónde tengo plata quieta',
    'dinero dormido',
    'cuentas que no uso',
    'plata parada en alguna cuenta',
  ],
  advice: [
    'qué me recomiendas',
    'qué me recomendás',
    'dónde puedo ahorrar',
    'dame consejos',
    'cómo puedo mejorar mis finanzas',
    'en qué puedo recortar',
    'tips para gastar menos',
    'qué debería hacer con mi plata',
  ],
  'data-query': [
    'cuánto gasté en uber vs taxi este trimestre',
    'promedio diario de gastos en mayo',
    'cuántas transacciones tuve la semana pasada',
    'gastos por cuenta este año',
    'cuánto gasté en promedio por mes',
    'compará mis gastos de mercado con los de restaurantes',
    'número de compras mayores a 100 mil',
    'cuánto ingresé este año',
    'gasto total agrupado por mes',
    'cuánto gasté entre marzo y mayo',
  ],
  help: [
    'ayuda',
    'qué sabes hacer',
    'qué puedo preguntarte',
    'cómo funcionas',
    'qué comandos hay',
  ],
}
