/**
 * Lista curada de iconos lucide permitidos en Finanzia.
 *
 * Regla: si necesitas un icono que no está acá, agrégalo aquí y solo aquí.
 * Esto evita que la app derive a un zoo visual y mantiene bundle ligero
 * (tree-shaking funciona porque importamos cada componente por nombre).
 *
 * Convención visual (mandato): stroke 1.5px, color currentColor, sin fill.
 */

import {
  // Navigation / shell
  Home,
  Wallet,
  List,
  Target,
  Sparkles,
  Settings,
  Command,
  Search,
  Filter,
  Bell,
  LogOut,
  User,

  // Finance — cuentas y movimiento
  CreditCard,
  Banknote,
  PiggyBank,
  Landmark,
  Coins,
  Bitcoin,
  ArrowUp,
  ArrowDown,
  ArrowRightLeft,
  TrendingUp,
  TrendingDown,

  // Acciones
  Plus,
  PlusCircle,
  Minus,
  Pencil,
  Trash2,
  Copy,
  Check,
  X,
  MoreHorizontal,
  MoreVertical,
  Upload,
  Download,
  RotateCcw,
  Link as LinkIcon,
  ExternalLink,

  // Estado e indicadores
  Loader,
  AlertCircle,
  AlertTriangle,
  Info,
  CheckCircle,
  XCircle,
  CircleDot,
  Circle,
  Eye,
  EyeOff,
  Lock,
  Unlock,

  // Dirección / chevrons
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ArrowLeft,
  ArrowRight,

  // Tiempo / etiquetas
  Calendar,
  Clock,
  Tag,

  // Categorías (subset del seed)
  Briefcase,
  PenTool,
  Gift,
  Car,
  CarFront,
  Fuel,
  Bus,
  Utensils,
  UtensilsCrossed,
  Coffee,
  Bike,
  ShoppingCart,
  ShoppingBag,
  Shirt,
  Lamp,
  Cpu,
  HeartPulse,
  Stethoscope,
  Pill,
  ShieldPlus,
  BookOpen,
  Book,
  GraduationCap,
  Newspaper,
  MonitorPlay,
  GlassWater,
  Film,
  Ticket,
  Scissors,
  Sparkle,
  Dumbbell,
  Phone,
  Repeat,
  Shield,
  Plane,
  HandHeart,
  Baby,
  PawPrint,
  Key,
  Plug,
  Wifi,
  Building,
  Wrench,
  ParkingCircle,
  Mail,
  type LucideIcon,
} from 'lucide-react'

export const icons = {
  home: Home,
  wallet: Wallet,
  list: List,
  target: Target,
  sparkles: Sparkles,
  settings: Settings,
  command: Command,
  search: Search,
  filter: Filter,
  bell: Bell,
  'log-out': LogOut,
  user: User,

  'credit-card': CreditCard,
  banknote: Banknote,
  'piggy-bank': PiggyBank,
  landmark: Landmark,
  coins: Coins,
  bitcoin: Bitcoin,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-right-left': ArrowRightLeft,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,

  plus: Plus,
  'plus-circle': PlusCircle,
  minus: Minus,
  pencil: Pencil,
  trash: Trash2,
  copy: Copy,
  check: Check,
  x: X,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  upload: Upload,
  download: Download,
  'rotate-ccw': RotateCcw,
  link: LinkIcon,
  'external-link': ExternalLink,

  loader: Loader,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  info: Info,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  'circle-dot': CircleDot,
  circle: Circle,
  eye: Eye,
  'eye-off': EyeOff,
  lock: Lock,
  unlock: Unlock,

  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,

  calendar: Calendar,
  clock: Clock,
  tag: Tag,

  briefcase: Briefcase,
  'pen-tool': PenTool,
  gift: Gift,
  car: Car,
  'car-front': CarFront,
  fuel: Fuel,
  bus: Bus,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  coffee: Coffee,
  bike: Bike,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  shirt: Shirt,
  lamp: Lamp,
  cpu: Cpu,
  'heart-pulse': HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  'shield-plus': ShieldPlus,
  'book-open': BookOpen,
  book: Book,
  'graduation-cap': GraduationCap,
  newspaper: Newspaper,
  'monitor-play': MonitorPlay,
  'glass-water': GlassWater,
  film: Film,
  ticket: Ticket,
  scissors: Scissors,
  sparkle: Sparkle,
  dumbbell: Dumbbell,
  phone: Phone,
  repeat: Repeat,
  shield: Shield,
  plane: Plane,
  'hand-heart': HandHeart,
  baby: Baby,
  'paw-print': PawPrint,
  key: Key,
  plug: Plug,
  wifi: Wifi,
  building: Building,
  wrench: Wrench,
  parking: ParkingCircle,
  mail: Mail,
} as const satisfies Record<string, LucideIcon>

export type IconName = keyof typeof icons

/** Resolver type-safe. Si el nombre no existe en el set curado, TS falla en compile. */
export function getIcon(name: IconName): LucideIcon {
  return icons[name]
}
